build: ignore command-line parameters while looking for tools
During configure, cc-check-tools looks for installed tools after
retrieving from environment the tool's name.

From Yocto Release 3.4 (honister) the variable RANLIB is set by
default as:
	RANLIB="ranlib -D"
The tool's parameter '-D' causes configure to fail with error
	Error: wrong # args: should be "find-executable name"

Let 'find-executable' and 'find-executable-path' to ignore any
parameter passed to the tool.

Signed-off-by: Antonio Borneo <borneo.antonio@gmail.com>